# Generated by Django 3.1 on 2021-10-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
