# Generated by Django 3.1 on 2021-10-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211007_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_received',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
