# Generated by Django 3.1 on 2021-10-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211008_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_shipped',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
